dist: xenial
sudo: required
language: python
python: "3.6.8"

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1

install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

env:
  global:
    - PGPORT=5433
    - DATABASE_URL="postgres://postgres@localhost:5433/ledger_test"

script: pytest

after_success: coveralls

notifications:
  email:
    recipients:
      - benjamin@bengfort.com
    on_success: change
    on_failure: always
